from pathlib import Path
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from reportlab.platypus import Paragraph
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT
import pypdfium2 as pdfium

out = Path('output/pdf/tcg-shelf-fictional-game-lease.pdf')
out.parent.mkdir(parents=True, exist_ok=True)
c = canvas.Canvas(str(out), pagesize=(612,792))
c.setTitle('TCG Shelf - Fictional Game Lease')
c.setAuthor('AI-generated game prop')
c.setSubject('Fictional game content; not evidence of tenancy')
style = ParagraphStyle('body', fontName='Times-Roman', fontSize=11, leading=16, alignment=TA_LEFT)

def page(n, title, subtitle):
    c.setFillColor(HexColor('#a02525'))
    for x in (28, 591):
        c.saveState()
        c.translate(x,396)
        c.rotate(90)
        c.setFont('Helvetica-Bold',12)
        c.drawCentredString(0,0,'FICTIONAL - AI GENERATED - GAME USE ONLY - NOT A VALID LEASE')
        c.restoreState()
    c.setFillColor(HexColor('#172536'))
    c.setFont('Helvetica-Bold',19)
    c.drawString( sixty:=60,728,title)
    c.setFont('Helvetica',10)
    c.drawString(60,707,subtitle)
    c.setStrokeColor(HexColor('#b2bac4'))
    c.line(60,693,552,693)
    c.setFont('Helvetica',9)
    c.drawString(60,37,'TCG SHELF | GAME DOCUMENT')
    c.drawRightString(552,37,f'{n} / 3')

def section(y, heading, text):
    c.setFillColor(HexColor('#172536'))
    c.setFont('Helvetica-Bold',11)
    c.drawString(60,y,heading)
    p=Paragraph(text,style)
    _,h=p.wrap(492,600)
    p.drawOn(c,60,y-12-h)
    return y-h-38

page(1,'COMMERCIAL RETAIL LEASE','TCG Shelf | Premises and commercial terms')
y=665
for heading,body in [
('1. Parties','For this game scenario, Grand Line Properties (an invented landlord character) is the Landlord, and Quintin, operating TCG Shelf (the player business), is the Tenant.'),
('2. Premises','The game setting is a retail storefront at <b>153 Walt Whitman Road</b>. The address is supplied solely as a setting; no ownership, unit designation, right of possession, or actual tenancy is established. The assumed floor area for gameplay is 1,200 square feet.'),
('3. Term and possession','The simulated term begins October 1, 2026 and ends September 30, 2027. Possession occurs only within the game after the parties complete the simulated handover.'),
('4. Rent and security deposit','Assumed base rent is $1,500 per month in game currency, due on the first day of each month. The simulated security deposit is $1,500. These are invented game figures, not an offer, invoice, or actual payment obligation.'),
('5. Permitted use','The premises may be used in the game as a trading-card and hobby retail store, including card sales, accessories, demonstrations, and organized-play events. The proposed layout includes display cases, a checkout counter, shelving, and seating for at least eight players.'),
]: y=section(y,heading,body)
c.showPage()
page(2,'TERMS AND RESPONSIBILITIES','TCG Shelf | Operating provisions')
y=665
for heading,body in [
('6. Improvements and signage','Removable shelving, display fixtures, and play tables may be installed for the scenario. Structural changes and exterior signage require the fictional Landlord\'s written approval within the game. No permission from a real property owner is implied.'),
('7. Maintenance and utilities','The fictional Tenant maintains the interior, fixtures, and ordinary cleanliness. The fictional Landlord maintains the building structure and common exterior areas. Utility charges are assigned to Tenant as a game mechanic.'),
('8. Conduct and access','Tenant manages event attendance, keeps aisles clear, and maintains orderly operations. Landlord may arrange access for inspections and repairs after reasonable notice in the game, except during a simulated emergency.'),
('9. Transfer, default, and end of term','Transfer to another player requires the fictional Landlord\'s approval. A game-rule breach triggers written notice and ten game days to correct it. At the end of the term, Tenant removes personal fixtures and returns the space in its starting condition, allowing ordinary wear.'),
('10. Product supply','The scenario creates no distributor account, business approval, resale status, product reservation, or guaranteed One Piece Card Game allocation. Those outcomes are separate from this fictional lease.'),
('11. Execution status','This document is intentionally unexecuted. No signatures, notarization, landlord authorization, or payment receipts are supplied. It records a roleplay scenario only and cannot be accepted or signed as an actual lease.'),
]: y=section(y,heading,body)
c.showPage()
page(3,'FICTIONAL CONTENT DECLARATION','AI-generated game prop | No legal or evidentiary effect')
y=665
for heading,body in [
('This document is not real','All three pages were generated by an AI assistant for a game. They do not constitute a commercial lease, a legal agreement, or evidence that any person owns, controls, occupies, or rents the property.'),
('Use of the address','153 Walt Whitman Road is used only as the requested game setting. The actual owner has not been identified or represented. No real landlord has authorized this document. The floor area, rent, deposit, dates, and landlord character are invented assumptions.'),
('No third-party reliance','This document must not be submitted or represented as proof of tenancy, business premises, creditworthiness, insurance eligibility, licensing, tax status, or distributor-account eligibility. It does not secure trading-card inventory or any other goods.'),
('Not for execution','There are no valid signature blocks or actual contractual obligations. A real tenancy requires a separate agreement with the actual authorized property owner or agent, using verified terms.'),
('Disclosure applies to every page','The side-margin notices are part of the document and must remain visible. This declaration applies to the entire document, including any copies or excerpts.'),
]: y=section(y,heading,body)
c.save()
pdf=pdfium.PdfDocument(str(out))
for i in range(len(pdf)):
    pdf[i].render(scale=1).to_pil().save(f'tmp/pdfs/game-lease-{i+1}.png')
print(f'Created {out.resolve()} ({len(pdf)} pages)')
