/**
 * Import the full English OPTCG catalog from punk-records into Supabase.
 *
 * Data source: https://github.com/buhbbl/punk-records (scraped from Bandai's official site)
 *
 * Usage:
 *   npm run import:catalog              # upsert into Supabase (needs service role key)
 *   npm run import:catalog -- --dry-run # fetch + transform only
 *   npm run import:catalog -- --sql     # write supabase/seed/catalog.sql
 *   npm run import:catalog -- --json    # write data/catalog.json
 */

import { createClient } from "@supabase/supabase-js";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Database } from "../lib/types/database";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const PUNK_BASE =
  "https://raw.githubusercontent.com/buhbbl/punk-records/main/english";
const CONCURRENCY = 32;
const UPSERT_BATCH = 400;

type CardInsert = Database["public"]["Tables"]["cards"]["Insert"];

type PunkPack = {
  id: string;
  raw_title: string;
  title_parts: {
    label: string | null;
    prefix: string | null;
    title: string;
  };
};

type PunkCard = {
  id: string;
  name: string;
  rarity: string;
  category: string;
  colors: string[];
  cost: number | null;
  attributes: string[];
  power: number | null;
  counter: number | null;
  pack_id: string;
  img_full_url: string;
};

function loadEnvFile(filename: string) {
  try {
    const text = readFileSync(join(ROOT, filename), "utf8");
    for (const line of text.split(/\r?\n/)) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eq = trimmed.indexOf("=");
      if (eq === -1) continue;
      const key = trimmed.slice(0, eq).trim();
      let value = trimmed.slice(eq + 1).trim();
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }
      if (!process.env[key]) process.env[key] = value;
    }
  } catch {
    // optional
  }
}

function normalizeRarity(rarity: string): string {
  const map: Record<string, string> = {
    Common: "Common",
    Uncommon: "Uncommon",
    Rare: "Rare",
    SuperRare: "Super Rare",
    SecretRare: "Secret Rare",
    Leader: "Leader",
    Special: "Special",
    TreasureRare: "Treasure Rare",
    Promo: "Promo",
  };
  return map[rarity] ?? rarity;
}

function normalizeType(category: string): string {
  if (category === "Don") return "DON!!";
  return category;
}

function packSetName(pack: PunkPack | undefined): string | null {
  if (!pack) return null;
  const { title, label } = pack.title_parts;
  if (label && title) return `${title} (${label})`;
  return title || pack.raw_title;
}

function toDbCard(card: PunkCard, packs: Record<string, PunkPack>): CardInsert {
  const pack = packs[card.pack_id];
  const colors = card.colors?.length ? card.colors.join("/") : null;
  const attributes = card.attributes?.length
    ? card.attributes.join("/")
    : null;

  return {
    card_number: card.id,
    name: card.name,
    set_name: packSetName(pack),
    rarity: normalizeRarity(card.rarity),
    color: colors,
    type: normalizeType(card.category),
    cost: card.cost != null ? String(card.cost) : null,
    power: card.power != null ? String(card.power) : null,
    counter: card.counter != null ? String(card.counter) : null,
    attribute: attributes,
    image_url: card.img_full_url,
  };
}

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
  }
  return res.json() as Promise<T>;
}

async function mapPool<T, R>(
  items: T[],
  worker: (item: T) => Promise<R>,
  concurrency: number,
): Promise<R[]> {
  const results: R[] = new Array(items.length);
  let next = 0;

  async function run() {
    while (true) {
      const i = next++;
      if (i >= items.length) return;
      results[i] = await worker(items[i]);
    }
  }

  await Promise.all(
    Array.from({ length: Math.min(concurrency, items.length) }, run),
  );
  return results;
}

function sqlEscape(value: string): string {
  return value.replace(/'/g, "''");
}

function cardsToSql(cards: CardInsert[]): string {
  const lines: string[] = [
    "-- Full OPTCG English catalog (generated by scripts/import-catalog.ts)",
    "-- Source: https://github.com/buhbbl/punk-records",
    "",
    "delete from public.cards where image_url like '%placehold.co%';",
    "",
  ];

  for (let i = 0; i < cards.length; i += 100) {
    const batch = cards.slice(i, i + 100);
    const values = batch
      .map((c) => {
        const cols = [
          c.card_number ? `'${sqlEscape(c.card_number)}'` : "null",
          `'${sqlEscape(c.name)}'`,
          c.set_name ? `'${sqlEscape(c.set_name)}'` : "null",
          c.rarity ? `'${sqlEscape(c.rarity)}'` : "null",
          c.color ? `'${sqlEscape(c.color)}'` : "null",
          c.type ? `'${sqlEscape(c.type)}'` : "null",
          c.cost ? `'${sqlEscape(c.cost)}'` : "null",
          c.power ? `'${sqlEscape(c.power)}'` : "null",
          c.counter ? `'${sqlEscape(c.counter)}'` : "null",
          c.attribute ? `'${sqlEscape(c.attribute)}'` : "null",
          c.image_url ? `'${sqlEscape(c.image_url)}'` : "null",
        ];
        return `  (${cols.join(", ")})`;
      })
      .join(",\n");

    lines.push(
      "insert into public.cards (card_number, name, set_name, rarity, color, type, cost, power, counter, attribute, image_url)",
      "values",
      values,
      "on conflict (card_number) do update set",
      "  name = excluded.name,",
      "  set_name = excluded.set_name,",
      "  rarity = excluded.rarity,",
      "  color = excluded.color,",
      "  type = excluded.type,",
      "  cost = excluded.cost,",
      "  power = excluded.power,",
      "  counter = excluded.counter,",
      "  attribute = excluded.attribute,",
      "  image_url = excluded.image_url;",
      "",
    );
  }

  return lines.join("\n");
}

async function fetchCatalog(): Promise<CardInsert[]> {
  console.log("Fetching pack metadata from punk-records…");
  const packs = await fetchJson<Record<string, PunkPack>>(
    `${PUNK_BASE}/packs.json`,
  );
  const packIds = Object.keys(packs);
  console.log(`Found ${packIds.length} packs. Downloading card data (${CONCURRENCY} parallel)…`);

  const packCards = await mapPool(packIds, async (packId) => {
    const cards = await fetchJson<PunkCard[]>(
      `${PUNK_BASE}/data/${packId}.json`,
    );
    return cards;
  }, CONCURRENCY);

  const flat = packCards.flat();
  const byId = new Map<string, CardInsert>();

  for (const card of flat) {
    byId.set(card.id, toDbCard(card, packs));
  }

  const catalog = [...byId.values()].sort((a, b) =>
    (a.card_number ?? "").localeCompare(b.card_number ?? ""),
  );

  console.log(
    `Transformed ${catalog.length} unique cards from ${flat.length} pack entries.`,
  );
  return catalog;
}

async function upsertToSupabase(cards: CardInsert[]) {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !serviceKey) {
    throw new Error(
      "Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local.\n" +
        "Add your Supabase service role key, or run with --sql / --json instead.",
    );
  }

  const supabase = createClient<Database>(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  console.log("Removing placeholder sample cards…");
  const { error: deleteError } = await supabase
    .from("cards")
    .delete()
    .like("image_url", "%placehold.co%");
  if (deleteError) {
    throw new Error(`Failed to clear sample cards: ${deleteError.message}`);
  }

  console.log(`Upserting ${cards.length} cards in batches of ${UPSERT_BATCH}…`);
  for (let i = 0; i < cards.length; i += UPSERT_BATCH) {
    const batch = cards.slice(i, i + UPSERT_BATCH);
    const { error } = await supabase
      .from("cards")
      .upsert(batch, { onConflict: "card_number" });
    if (error) {
      throw new Error(
        `Upsert failed at batch ${i / UPSERT_BATCH + 1}: ${error.message}`,
      );
    }
    process.stdout.write(
      `\r  ${Math.min(i + UPSERT_BATCH, cards.length)} / ${cards.length}`,
    );
  }
  console.log("\nDone.");
}

async function main() {
  loadEnvFile(".env.local");
  loadEnvFile(".env");

  const args = new Set(process.argv.slice(2));
  const dryRun = args.has("--dry-run");
  const writeSql = args.has("--sql");
  const writeJson = args.has("--json");

  const started = Date.now();
  const catalog = await fetchCatalog();

  const sets = new Set(catalog.map((c) => c.set_name).filter(Boolean));
  console.log(`Sets: ${sets.size}`);
  console.log(`Sample: ${catalog[0]?.card_number} — ${catalog[0]?.name}`);

  if (dryRun) {
    console.log(`Dry run complete (${((Date.now() - started) / 1000).toFixed(1)}s).`);
    return;
  }

  if (writeJson) {
    const out = join(ROOT, "data", "catalog.json");
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, JSON.stringify(catalog, null, 2));
    console.log(`Wrote ${catalog.length} cards to ${out}`);
  }

  if (writeSql) {
    const out = join(ROOT, "supabase", "seed", "catalog.sql");
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, cardsToSql(catalog));
    console.log(`Wrote SQL seed to ${out}`);
  }

  if (!writeJson && !writeSql) {
    await upsertToSupabase(catalog);
  }

  console.log(`Finished in ${((Date.now() - started) / 1000).toFixed(1)}s.`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
