# One-shot local dev bootstrap for One Piece TCG Collection.
# Prerequisites: Node.js, Docker Desktop (running).
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

$nodeDir = "C:\Program Files\nodejs"
if (Test-Path $nodeDir) {
  $env:Path = "$nodeDir;$env:Path"
}
$env:NODE_OPTIONS = "--use-system-ca"

function Test-DockerRunning {
  try {
    $null = docker info 2>$null
    return $LASTEXITCODE -eq 0
  } catch {
    return $false
  }
}

function Write-EnvLocal {
  $envOutput = npx supabase status -o env `
    --override-name api.url=NEXT_PUBLIC_SUPABASE_URL `
    --override-name anon.key=NEXT_PUBLIC_SUPABASE_ANON_KEY `
    --override-name service_role.key=SUPABASE_SERVICE_ROLE_KEY 2>&1

  if ($LASTEXITCODE -ne 0) {
    throw "Failed to read Supabase status: $envOutput"
  }

  $lines = @(
    "# Auto-generated by scripts/setup-dev.ps1 — local Supabase",
    ""
  )
  $lines += ($envOutput | Where-Object { $_ -match "=" })
  $lines += ""
  Set-Content -Path (Join-Path $Root ".env.local") -Value $lines -Encoding utf8
}

Write-Host "==> Installing npm dependencies..."
npm install

if (-not (Test-DockerRunning)) {
  Write-Host ""
  Write-Host "Docker is not installed or not running." -ForegroundColor Yellow
  Write-Host "Local Supabase needs Docker Desktop:"
  Write-Host "  winget install Docker.DockerDesktop"
  Write-Host "Start Docker Desktop, then re-run: npm run setup"
  Write-Host ""
  Write-Host "Or use hosted Supabase: copy .env.local.example to .env.local and fill in your project keys."
  exit 1
}

Write-Host "==> Starting local Supabase (first run downloads images; may take a few minutes)..."
npx supabase start

Write-Host "==> Applying database migrations..."
npx supabase db reset --yes

Write-Host "==> Writing .env.local..."
Write-EnvLocal

Write-Host "==> Importing full OPTCG catalog (~4.5k cards)..."
npm run import:catalog

Write-Host ""
Write-Host "Setup complete." -ForegroundColor Green
Write-Host "  App:           npm run dev  →  http://localhost:3000"
Write-Host "  Supabase Studio: http://127.0.0.1:54323"
Write-Host "  Test email inbox: http://127.0.0.1:54324"
